// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neon-vinyl/NeonVinylPlayer.tsx": () => import("../components/mockups/neon-vinyl/NeonVinylPlayer.tsx"),
  "./components/mockups/templates/DarkAIRenderMusicPlayer-syCzEP/App.tsx": () => import("../components/mockups/templates/DarkAIRenderMusicPlayer-syCzEP/App.tsx"),
  "./components/mockups/templates/NeonMusicPlayer-gMhKDC/NowPlaying.tsx": () => import("../components/mockups/templates/NeonMusicPlayer-gMhKDC/NowPlaying.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-rCwtfJ/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-rCwtfJ/DeepOrangePoster.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-vOgsn-/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-vOgsn-/DinnerPartyPosterSeverance.tsx")
};
